name: AlmaLinux VM Deployment with Jenkins Setup

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 1: Check if the resource group exists
    - name: Check Resource Group
      run: |
        if az group exists --name divergenceRG2; then
          echo "Resource Group exists."
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "Resource Group does not exist."
          echo "exists=false" >> $GITHUB_ENV
        fi

    # Step 2: Create Resource Group if not exists
    - name: Create Resource Group
      if: env.exists == 'false'
      run: |
        az group create --name divergenceRG2 --location eastus

    # Step 3: Create Networking Components (Virtual Network, Subnet, NSG, Public IP, NIC)
    - name: Create Virtual Network and Subnet
      run: |
        az network vnet create --resource-group divergenceRG2 --name AlmaLinuxVNet --subnet-name AlmaLinuxSubnet

    - name: Create Network Security Group (NSG)
      run: |
        az network nsg create --resource-group divergenceRG2 --name AlmaLinuxNSG

    - name: Create Public IP
      run: |
        az network public-ip create --resource-group divergenceRG2 --name AlmaLinuxPublicIP --allocation-method Static

    - name: Create Network Interface (NIC)
      run: |
        az network nic create --resource-group divergenceRG2 --name AlmaLinuxNIC --vnet-name AlmaLinuxVNet --subnet AlmaLinuxSubnet --network-security-group AlmaLinuxNSG --public-ip-address AlmaLinuxPublicIP

    # Step 4: Create AlmaLinux VM with the Public IP attached
    - name: Create AlmaLinux VM
      run: |
        az vm create \
          --resource-group divergenceRG2 \
          --name AlmaLinuxVM \
          --image ${{ steps.image-search.outputs.image-urn }} \
          --admin-username azureuser \
          --nics AlmaLinuxNIC \
          --generate-ssh-keys

    # Step 5: Retry Public IP Assignment (Loop until available or timeout)
    - name: Retrieve Public IP Address
      run: |
        for i in {1..10}; do
          echo "Attempt $i: Checking for public IP..."
          public_ip=$(az network public-ip show --resource-group divergenceRG2 --name AlmaLinuxPublicIP --query ipAddress -o tsv)
          if [ -n "$public_ip" ]; then
            echo "Public IP: $public_ip"
            echo "public_ip=$public_ip" >> $GITHUB_ENV
            break
          else
            echo "Public IP not assigned yet. Retrying in 30 seconds..."
            sleep 30
          fi
          if [ $i -eq 10 ]; then
            echo "Failed to retrieve Public IP after multiple attempts."
            exit 1
          fi
        done

    # Step 6: Install Jenkins on the AlmaLinux VM using SSH
    - name: Install Jenkins on AlmaLinux VM
      run: |
        ssh -o StrictHostKeyChecking=no -i /home/runner/.ssh/id_rsa azureuser@${{ env.public_ip }} <<EOF
        sudo yum update -y
        sudo yum install -y java-11-openjdk
        sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        sudo yum install -y jenkins
        sudo systemctl enable jenkins
        sudo systemctl start jenkins
        EOF

    # Step 7: Open Ports in NSG for HTTP, Jenkins, and SSH
    - name: Open Ports in NSG for HTTP and Jenkins
      run: |
        az network nsg rule create \
          --resource-group divergenceRG2 \
          --nsg-name AlmaLinuxNSG \
          --name AllowHTTP \
          --protocol tcp \
          --priority 1001 \
          --destination-port-ranges 80 \
          --access allow

    - name: Open Ports in NSG for Jenkins
      run: |
        az network nsg rule create \
          --resource-group divergenceRG2 \
          --nsg-name AlmaLinuxNSG \
          --name AllowJenkins \
          --protocol tcp \
          --priority 1002 \
          --destination-port-ranges 8080 \
          --access allow

    - name: Open Ports in NSG for SSH
      run: |
        az network nsg rule create \
          --resource-group divergenceRG2 \
          --nsg-name AlmaLinuxNSG \
          --name AllowSSH \
          --protocol tcp \
          --priority 1003 \
          --destination-port-ranges 22 \
          --access allow

    # Step 8: Cleanup on failure
    - name: Cleanup on Failure
      if: failure()
      run: |
        if az group exists --name divergenceRG2; then
          echo "Cleaning up resources due to failure..."
          az group delete --name divergenceRG2 --yes --no-wait
        else
          echo "No resource group found for cleanup."
