name: Deploy AlmaLinux VM with Automated Image Selection

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: |
        az group create --name divergenceRG --location eastus

    - name: Query Available AlmaLinux Images
      id: image-search
      run: |
        az vm image list --offer almalinux --all --output json > image_list.json
        latest_image=$(jq -r 'sort_by(.version) | reverse | .[] | select(.offer == "almalinux") | .urn' image_list.json | head -n 1)
        echo "Latest AlmaLinux Image URN: $latest_image"
        echo "::set-output name=image-urn::$latest_image"

    - name: Debug:Print Image URN
      run: echo "Selected Image URN:${{ steps.image-search.outputs.image-urn }}"

    - name: Create AlmaLinux VM
      run: |
        if [ -z "${{ steps.image-search.outputs.image-urn }}" ]; then
          echo "No valid image URN found. Exiting."
          exit 1
        fi
        az vm create \
          --resource-group divergenceRG \
          --name AlmaLinuxVM \
          --image ${{ steps.image-search.outputs.image-urn }} \
          --admin-username azureuser \
          --generate-ssh-keys

    - name: Open Ports in NSG
      run: |
        az network nsg rule create \
          --resource-group divergenceRG \
          --nsg-name AlmaLinuxVMNSG \
          --name AllowHTTPAndJenkins \
          --protocol tcp \
          --priority 1000 \
          --destination-port-ranges 80 8080 22 \
          --access allow

    - name: Install Jenkins on AlmaLinux VM
      run: |
        ssh -i /home/runner/.ssh/id_rsa azureuser@$(az vm show --resource-group divergenceRG --name AlmaLinuxVM --show-details --query [publicIpAddress] -o tsv) <<EOF
        sudo yum update -y
        sudo yum install -y java-11-openjdk
        sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        sudo yum install -y jenkins
        sudo systemctl enable jenkins
        sudo systemctl start jenkins
        EOF
